### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by hjlee9182** [minzwon/sota-music-tagging-models#4]
Your model has Mel spectrogram transform.
So if model's forward, that's also work.

I have one question.
 
Used already makes npy(mel spectrogram) and model using npy vs When the model is operated, make it into a mel spectrogram( your code) 
Upper two situation, is there difference?
and how about harmonic transform situation?

**Comment by minzwon** [comment]
Hi,

For the first question, if you used the same parameters for the Mel spectrogram, the results have to be identical. However, based on the STFT library that you used, the results can be slightly different. So please double-check if your preprocessing library uses the same STFT module from 'torchaudio'.

In the case of harmonic transform, since the architecture uses a learnable front-end, you cannot perform preprocessing for that.

**Comment by minzwon** [comment]
Closing this issue.
